export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const SEARCH_PRODUCT ='SEARCH_PRODUCT';
export const FETCH_PRODUCT_BY_TASK = 'FETCH_PRODUCT_BY_TASK';
export const FETCH_CARTS = 'FETCH_CARTS';
export const UPDATE_CARTS = 'UPDATE_CARTS';
